name: cubere
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.7
  logger: ^1.1.0
  freezed_annotation:
  dartz: ^0.10.0
  firebase_core: ^1.7.0
  firebase_analytics: ^8.3.3
  firebase_auth: ^3.1.2
  firebase_storage: ^10.0.4
  cloud_firestore: ^2.5.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  freezed:
  json_serializable:
flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
